services:
  postgres-dev:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/miyagami/data

volumes:
  postgres_data:
